


@startuml
skinparam componentStyle uml2
skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

[controller] <<..ru.onixred.siberian.sea.battle.layer.controller..>>
[dao] <<..ru.onixred.siberian.sea.battle.layer.dao..>>
[model] <<..ru.onixred.siberian.sea.battle.layer.model..>>
[service] <<..ru.onixred.siberian.sea.battle.layer.service..>>
[acl] <<..ru.onixred.siberian.sea.battle.layer.acl..>>
[repository] <<..ru.onixred.siberian.sea.battle.layer.repository..>>

[controller] --> [model]
[controller] --> [service]

[service] --> [model]
[service] --> [acl]
[service] --> [repository]

[dao] --> [model]

[repository] --> [dao]
[repository] --> [model]

[acl] --> [model]
[acl] --> [dao]

@enduml